### PR TITLE
Fix video stretching

### LINKED ISSUE #11: Fix video stretching
Transcoding doesn't preserve the original aspect ratio, leading to stretching/squashing.

From conversation with Mina:

here are the docs for tweaking the width and height of the video to maintain aspect ratio:

https://trac.ffmpeg.org/wiki/Scaling%20(resizing)%20with%20ffmpeg
https://ffmpeg.org/ffmpeg-filters.html#scale

i think the `force_original_aspect_ratio` option might be the way to go. you give it the dimensions of the bounding box and it makes the video fit within those dimensions (although the video could be of variable size depending on the input video dimensions). to get around that variable video size so it’s always 1920x1080 without stretching you can pad it out so that it’s letterboxed with something like:

`"scale=1920:1080:force_original_aspect_ratio=decrease,pad=1920:1080:(ow-iw)/2:(oh-ih)/2"`

### PR DESCRIPTION
**Pull request by devonoel**
Fixes #11, so aspect ratio will be preserved, and some black bars will be added to the sides of any videos in a weird aspect ratio when scaling to 1080p. There's a couple little other things too. 

I removed `streamio-ffmpeg` entirely. Its pretty restrictive with what it allows, and doesn't really add much, so its not really worth the trouble of using given our fairly complex use case.

I also slightly recoloured the GA watermark so that it doesn't blend in with the black bars added by scaling some videos to 1080p.

### CODE REVIEW

**Comment by devonoel** [comment]
Oh, and I also switched from having an option for resolution to separating them out into width and height

**Comment by devonoel** [comment]
I'm just gonna merge this @fightingtheboss but let me know if you have any comments or whatever.

**Comment by fightingtheboss** [comment]
Looks pretty good.

I was curious if the `ProcessHelpers` module was useful, seems as though you came to the same conclusion.

Interesting that you've dropped the dependency on the `streamio-ffmpeg` gem in favour of using system calls directly. Definitely more flexibility this way, at the expense of less clarity, but I figure that's generally going to be the tradeoff with ffmpeg, where nothing is ever really that clear.

**Comment by devonoel** [comment]
Yeah, its actually not really any easier to use `streamio-ffmpeg` given our use case, its pretty limited in what it can do, so we'd end up having to bend over backwards to use it in a way its not designed to be used, or patch the library ourselves.

It basically got to the point where I'd just be using `filter_complex` for pretty much every call, which is possible but I think less clear with `streamio-ffmpeg` than just doing direct system calls, so it wasn't really worth keeping around.

**Pull request merged**
